name: rl-gym-retro
channels:
  - defaults
dependencies:
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_1
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - ncurses=6.2=h0a44026_0
  - openssl=1.1.1e=h1de35cc_0
  - pip=20.0.2=py37_1
  - python=3.7.7=hc70fcce_0_cpython
  - readline=8.0=h1de35cc_0
  - setuptools=46.1.1=py37_0
  - sqlite=3.31.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - cloudpickle==1.3.0
    - future==0.18.2
    - gym==0.17.1
    - gym-retro==0.7.1
    - numpy==1.18.2
    - pyglet==1.5.0
    - scipy==1.4.1
    - six==1.14.0
prefix: /anaconda3/envs/rl-gym-retro

