name: rl-gym-retro
channels:
  - defaults
dependencies:
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_1
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - ncurses=6.2=h0a44026_0
  - openssl=1.1.1e=h1de35cc_0
  - pip=20.0.2=py37_1
  - python=3.7.7=hc70fcce_0_cpython
  - readline=8.0=h1de35cc_0
  - setuptools=46.1.1=py37_0
  - sqlite=3.31.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - absl-py==0.10.0
    - astor==0.8.1
    - atari-py==0.2.6
    - attrs==20.2.0
    - cffi==1.14.3
    - click==7.1.2
    - cloudpickle==1.2.2
    - cython==0.29.21
    - fasteners==0.15
    - ffmpeg==1.4
    - future==0.18.2
    - gast==0.4.0
    - glfw==2.0.0
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - gym==0.15.7
    - gym-retro==0.7.1
    - h5py==2.10.0
    - imageio==2.9.0
    - importlib-metadata==2.0.0
    - iniconfig==1.0.1
    - joblib==0.17.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - markdown==3.2.2
    - monotonic==1.5
  #  - mujoco-py==2.0.2.13
    - numpy==1.18.2
    - opencv-python==4.4.0.44
    - packaging==20.4
    - pillow==7.2.0
    - pluggy==0.13.1
    - protobuf==3.13.0
    - py==1.9.0
    - pycparser==2.20
    - pyglet==1.5.0
    - pyparsing==2.4.7
    - pytest==6.1.0
    - scipy==1.4.1
    - six==1.14.0
    - tensorboard==1.14.0
    - tensorflow==1.14.0
    - tensorflow-estimator==1.14.0
    - termcolor==1.1.0
    - toml==0.10.1
    - tqdm==4.50.0
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - zipp==3.2.0
prefix: /opt/anaconda3/envs/rl-gym-retro
